
---
- name: deploy_app_to_swarm
  hosts: app-back 
  become: yes
  gather_facts: false

  roles:
    - { role: roles/deploy_nginx }  
    - { role: roles/deploy_postgres }    
    - { role: roles/deploy_app_to_swarm }
    - { role: roles/portainer } # galaxy role 
