---


- name: Install docker packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "{{ apt_packages }}"
  tags: docker

- name: Install pip package
  pip:
    name: "{{ item }}"
  with_items:
    - "{{ pip_packages }}"

